const STAGES=["New Inquiry","Appointment","CAD / Quote","Negotiation","Deposit Paid","Production","Ready / Pickup","Won","Lost"];
const seedLeads=[
{id:1,name:"Marcus R.",contact:"Instagram",interest:"14K 12mm Cuban chain",value:7200,source:"Instagram",stage:"Negotiation",nextAction:"Follow up on financing options",due:true},
{id:2,name:"Samantha D.",contact:"Website",interest:"2.0ct oval engagement ring",value:6400,source:"Website",stage:"CAD / Quote",nextAction:"Send revised halo CAD",due:true},
{id:3,name:"Luis A.",contact:"Walk-in",interest:"Diamond nameplate",value:1800,source:"Walk-in",stage:"Deposit Paid",nextAction:"Confirm spelling before production",due:false},
{id:4,name:"Tasha W.",contact:"Referral",interest:"Memorial pendant",value:3100,source:"Referral",stage:"Appointment",nextAction:"Confirm Saturday consultation",due:true},
{id:5,name:"Andre K.",contact:"Phone",interest:"Rolex trade + upgrade",value:9800,source:"Phone",stage:"New Inquiry",nextAction:"Request watch photos and reference",due:true},
{id:6,name:"Nicole M.",contact:"Instagram",interest:"Tennis bracelet",value:4250,source:"Instagram",stage:"Won",nextAction:"Ask for review after pickup",due:false}
];
const seedJobs=[
{id:1,name:"Samantha D.",item:"Oval halo engagement ring",stage:"CAD",due:"Revision due today"},
{id:2,name:"Luis A.",item:"Diamond nameplate",stage:"Production",due:"Target: Sep 12"},
{id:3,name:"Tasha W.",item:"Memorial pendant",stage:"Consult",due:"Appointment: Saturday"},
{id:4,name:"Marcus R.",item:"12mm Cuban chain",stage:"Quote",due:"Financing follow-up"},
{id:5,name:"Nicole M.",item:"Tennis bracelet",stage:"Pickup",due:"Ready today"}
];
let leads=JSON.parse(localStorage.getItem("hogOSLeads")||"null")||seedLeads;
let jobs=JSON.parse(localStorage.getItem("hogOSJobs")||"null")||seedJobs;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(n)||0);
function persist(){localStorage.setItem("hogOSLeads",JSON.stringify(leads));localStorage.setItem("hogOSJobs",JSON.stringify(jobs));}
function toast(msg){const el=$("#toast");el.textContent=msg;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2200);}
function switchTab(tab){$$('.app-nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$$('.app-view').forEach(v=>v.classList.remove('active'));$(`#view-${tab}`).classList.add('active');const map={dashboard:["Command center","Good morning."],leads:["Revenue pipeline","Every opportunity in one place."],jobs:["Custom workflow","Know exactly where every job stands."],assistant:["Sales assistant","Make the next follow-up easier."]};$("#viewEyebrow").textContent=map[tab][0];$("#viewTitle").textContent=map[tab][1];renderAll();}
function buildStageOptions(){const opts=STAGES.map(s=>`<option value="${s}">${s}</option>`).join('');$("#newLeadStage").innerHTML=opts;$("#stageFilter").innerHTML=`<option value="all">All stages</option>${opts}`;}
function renderDashboard(){const open=leads.filter(l=>!["Won","Lost"].includes(l.stage));$("#pipelineValue").textContent=fmt(open.reduce((a,l)=>a+l.value,0));$("#openLeads").textContent=open.length;$("#followupsDue").textContent=leads.filter(l=>l.due&&l.stage!=="Lost").length;$("#wonValue").textContent=fmt(leads.filter(l=>l.stage==="Won").reduce((a,l)=>a+l.value,0));
const counts=STAGES.filter(s=>!['Lost'].includes(s)).map(s=>({s,c:leads.filter(l=>l.stage===s).length,v:leads.filter(l=>l.stage===s).reduce((a,l)=>a+l.value,0)}));const max=Math.max(1,...counts.map(x=>x.v));$("#stageBars").innerHTML=counts.filter(x=>x.c||["New Inquiry","CAD / Quote","Negotiation","Won"].includes(x.s)).map(x=>`<div class="stage-row"><span>${x.s}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(4,(x.v/max)*100)}%"></div></div><strong>${x.c}</strong></div>`).join('');
const due=leads.filter(l=>l.due&&!["Lost"].includes(l.stage)).slice(0,5);$("#followupList").innerHTML=due.length?due.map(l=>`<div class="followup-item"><span class="followup-dot"></span><div><strong>${l.name} · ${l.interest}</strong><small>${l.nextAction||l.stage}</small></div><button data-assist="${l.id}">Draft</button></div>`).join(''):`<small style="color:#77818d">Nothing due right now.</small>`;$$('[data-assist]').forEach(b=>b.onclick=()=>{switchTab('assistant');$("#assistantLead").value=b.dataset.assist;generateMessage();});}
function renderLeads(){const q=$("#leadSearch")?.value.toLowerCase()||'';const stage=$("#stageFilter")?.value||'all';const rows=leads.filter(l=>(stage==='all'||l.stage===stage)&&[l.name,l.interest,l.source,l.contact].join(' ').toLowerCase().includes(q));$("#leadTableBody").innerHTML=rows.length?rows.map(l=>`<tr><td><strong>${l.name}</strong><br><span style="color:#737d89">${l.contact||''}</span></td><td>${l.interest}</td><td>${fmt(l.value)}</td><td><select class="stage-select" data-stage-id="${l.id}">${STAGES.map(s=>`<option ${s===l.stage?'selected':''}>${s}</option>`).join('')}</select></td><td>${l.nextAction||'—'}${l.due?' <span class="pill hot">Due</span>':''}</td><td><button class="row-action" data-row-assist="${l.id}">Draft follow-up</button></td></tr>`).join(''):`<tr><td colspan="6">No matching leads.</td></tr>`;$$('[data-stage-id]').forEach(s=>s.onchange=()=>{const l=leads.find(x=>x.id==s.dataset.stageId);l.stage=s.value;if(s.value==='Won')l.due=false;persist();renderAll();toast(`${l.name} moved to ${s.value}`);});$$('[data-row-assist]').forEach(b=>b.onclick=()=>{switchTab('assistant');$("#assistantLead").value=b.dataset.rowAssist;generateMessage();});}
function renderJobs(){const columns=["Consult","CAD","Quote","Production","Pickup"];$("#jobBoard").innerHTML=columns.map(stage=>`<div class="job-column"><h4>${stage} · ${jobs.filter(j=>j.stage===stage).length}</h4>${jobs.filter(j=>j.stage===stage).map(j=>`<div class="job-card"><strong>${j.name}</strong><small>${j.item}</small><small>${j.due}</small></div>`).join('')||'<small style="color:#616b77">No jobs</small>'}</div>`).join('');}
function renderAssistant(){const current=$("#assistantLead")?.value;$("#assistantLead").innerHTML=leads.filter(l=>l.stage!=="Lost").map(l=>`<option value="${l.id}">${l.name} — ${l.interest}</option>`).join('');if(current&&leads.some(l=>String(l.id)===String(current)))$("#assistantLead").value=current;}
function renderAll(){$("#leadCountBadge").textContent=leads.filter(l=>!["Won","Lost"].includes(l.stage)).length;renderDashboard();renderLeads();renderJobs();renderAssistant();}
function generateMessage(){const lead=leads.find(l=>String(l.id)===$("#assistantLead").value);if(!lead)return;const tone=$("#assistantTone").value;const goal=$("#assistantGoal").value;let msg='';if(goal==='Close deposit')msg=`Hi ${lead.name.split(' ')[0]}, I wanted to follow up on the ${lead.interest}. We can lock in the next step with the deposit and keep everything moving. Want me to take care of that for you today?`;else if(goal==='Book appointment')msg=`Hi ${lead.name.split(' ')[0]}, I wanted to follow up on the ${lead.interest}. I can have everything ready so you can see the options without wasting time. Would today or tomorrow be better for you to stop in?`;else if(goal==='Re-engage')msg=`Hi ${lead.name.split(' ')[0]}, checking back on the ${lead.interest}. I still have your details and can pick up exactly where we left off. Are you still looking to move forward with it?`;else msg=`Hi ${lead.name.split(' ')[0]}, just following up on the ${lead.interest}. ${lead.nextAction?lead.nextAction+'. ':''}If you have any questions, I can help you get the next step handled today.`;
if(tone==='Short')msg=msg.replace(/ I wanted to follow up on/g,' Following up on').replace(/If you have any questions, /,'');if(tone==='Luxury')msg=msg.replace('I can have everything ready','I can prepare the options specifically for you').replace('stop in','come in for a private look');if(tone==='Direct')msg=msg.replace('Would today or tomorrow be better for you to stop in?','Can you come in today or tomorrow?');$("#assistantMessage").textContent=msg;}
function addLeadFromForm(e){e.preventDefault();const f=new FormData($("#leadForm"));const lead={id:Date.now(),name:f.get('name').trim(),contact:f.get('contact').trim(),interest:f.get('interest').trim(),value:Number(f.get('value')||0),source:f.get('source'),stage:f.get('stage'),nextAction:f.get('nextAction').trim(),due:true};leads.unshift(lead);persist();$("#leadDialog").close();$("#leadForm").reset();renderAll();switchTab('leads');toast('Lead added to pipeline');}
function saveBetaRequest(e){e.preventDefault();const f=Object.fromEntries(new FormData($("#betaForm")).entries());const reqs=JSON.parse(localStorage.getItem('hogOSBetaRequests')||'[]');reqs.unshift({...f,id:Date.now(),createdAt:new Date().toISOString()});localStorage.setItem('hogOSBetaRequests',JSON.stringify(reqs));$("#betaDialog").close();$("#betaForm").reset();toast('Founding request saved in prototype');}
$$('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));$$('.app-nav').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$$('[data-tab-jump]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tabJump));$("#addLeadBtn").onclick=()=>$("#leadDialog").showModal();$("#betaRequestBtn").onclick=()=>$("#betaDialog").showModal();$("#leadForm").addEventListener('submit',addLeadFromForm);$("#betaForm").addEventListener('submit',saveBetaRequest);$("#leadSearch").addEventListener('input',renderLeads);$("#stageFilter").addEventListener('change',renderLeads);$("#generateMessageBtn").onclick=generateMessage;$("#copyMessageBtn").onclick=async()=>{const t=$("#assistantMessage").textContent;try{await navigator.clipboard.writeText(t);toast('Message copied');}catch{toast('Select the message and copy it');}};
buildStageOptions();renderAll();